import {chromium, expect} from '@playwright/test';
import {mkdtempSync, mkdirSync, rmSync, writeFileSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {resolve, dirname, join} from 'node:path';
import {fileURLToPath} from 'node:url';
import {execFileSync} from 'node:child_process';

const cli = resolve(dirname(fileURLToPath(import.meta.url)), '../scripts/kanban.py');
const state = mkdtempSync(join(tmpdir(), 'agent-kanban-browser-'));
const output = resolve(process.argv[2] || 'kanban-browser-results');
mkdirSync(output, {recursive:true});
const run = (...args) => JSON.parse(execFileSync('python3', [cli,'--state',state,'--actor','lead',...args], {encoding:'utf8'}));
let browser;
try {
  run('init','--title','A shared application','--goal','Shared behavior. Independent interfaces. A clear view of every agent’s work.');
  const names = ['Design the navigation contract','Implement the Rust state model','Review independent screen layouts','Connect the native device','Verify saved changes survive reload'];
  for (let i=0;i<5;i++) run('add',`task-0${i+1}`,'--title',names[i],'--description','A bounded outcome with an assigned agent, clear acceptance criteria, and recorded evidence.','--assignee',i%2?'implementation agent':'lead','--reviewer','lead','--criterion','The agreed observable behavior works.','--priority',i===0?'high':'normal');
  run('claim','task-02');
  run('move','task-03','--status','in_review','--evidence','Focused checks passed; awaiting lead review.');
  run('move','task-04','--status','blocked','--blocker','Waiting for a matching device.');
  run('move','task-05','--status','done','--evidence','Lead inspected the source and the focused browser check passed.');
  run('add','task-06','--title','<img src=x onerror=alert(1)>','--description','Literal untrusted text must never become markup.','--assignee','implementation agent');
  run('board','--summary','Agents update this board as work moves from planning through review.');
  const server=run('start','--port','0');
  browser=await chromium.launch({headless:true});
  const page=await browser.newPage({viewport:{width:1500,height:980}});
  const errors=[];
  page.on('pageerror',e=>errors.push(e.message));
  await page.goto(server.local_url);
  await expect(page.locator('.connection')).toContainText('Live');
  await expect(page.locator('.column')).toHaveCount(5);
  await expect(page.locator('.card')).toHaveCount(6);
  await expect(page.locator('img')).toHaveCount(0);
  await expect(page.locator('[draggable="true"],textarea,[contenteditable="true"]')).toHaveCount(0);
  await page.screenshot({path:join(output,'desktop.png'),fullPage:true});
  await page.getByRole('button',{name:'task-03: Review independent screen layouts'}).click();
  await expect(page.getByRole('dialog')).toContainText('Focused checks passed');
  await expect(page.getByRole('dialog')).toContainText('Acceptance criteria');
  await page.screenshot({path:join(output,'detail.png')});
  await page.keyboard.press('Escape');
  await page.getByRole('searchbox').fill('native device');
  await expect(page.locator('.card')).toHaveCount(1);
  await page.getByRole('searchbox').fill('');
  await page.getByRole('combobox').selectOption('implementation agent');
  await expect(page.locator('.card')).toHaveCount(2);
  await page.getByRole('combobox').selectOption('');
  run('claim','task-01');
  await expect(page.locator('.column.in_progress .card')).toHaveCount(2,{timeout:10000});
  await page.getByRole('button',{name:'Activity',exact:true}).click();
  await expect(page.locator('#activity')).toContainText('Claimed work');
  await page.getByRole('button',{name:'Activity',exact:true}).click();
  await page.setViewportSize({width:390,height:844});
  await page.screenshot({path:join(output,'mobile.png'),fullPage:true});
  const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth);
  expect(overflow).toBe(false);
  await page.locator('.column.blocked').scrollIntoViewIfNeeded();
  await page.getByRole('button',{name:'task-04: Connect the native device'}).click();
  await expect(page.getByRole('dialog')).toContainText('Waiting for a matching device.');
  await page.keyboard.press('Escape');
  await page.context().setOffline(true);
  await expect(page.locator('.connection')).toContainText('Disconnected',{timeout:12000});
  await expect(page.locator('.card')).toHaveCount(6);
  await page.context().setOffline(false);
  await expect(page.locator('.connection')).toContainText('Live',{timeout:12000});
  run('board','--mode','paused','--summary','Work paused at the usage checkpoint.');
  await expect(page.locator('#summary')).toContainText('Paused',{timeout:10000});
  expect(errors).toEqual([]);
  writeFileSync(join(output,'browser.json'),JSON.stringify({passed:true,checks:['five columns','read only controls','literal task text','detail evidence','search','agent filter','live CLI updates','activity','mobile horizontal board without page overflow','disconnected stale view','reconnection','paused mode'],consoleErrors:errors},null,2)+'\n');
  console.log('Browser checks passed; screenshots saved.');
} finally {
  await browser?.close();
  run('stop');
  rmSync(state,{recursive:true,force:true});
}
